export type LanguageCode = "ar" | "en" | "fr" | "de";

export interface VocabItem {
  id: string;
  emoji: string;
  ar: { letter: string; letterSpeech: string; word: string; wordSpeech: string };
  en: { letter: string; letterSpeech: string; word: string; wordSpeech: string };
  fr: { letter: string; letterSpeech: string; word: string; wordSpeech: string };
  de: { letter: string; letterSpeech: string; word: string; wordSpeech: string };
}

export interface Card {
  id: string; // Unique instance ID (e.g. apple-1, apple-2)
  itemId: string; // Refers to VocabItem.id
  type: "letter" | "picture" | "word" | "audio";
  content: string; // Displays Letter, Emoji, Word, or Speaker icon
  isFlipped: boolean;
  isMatched: boolean;
  isCelebrating: boolean;
}

export type GameDifficulty = "easy" | "medium" | "hard";

export interface GameModeInfo {
  id: number;
  unlockedByDefault: boolean;
  title: Record<LanguageCode, string>;
  description: Record<LanguageCode, string>;
}

export const VOCAB_ITEMS: VocabItem[] = [
  {
    id: "apple",
    emoji: "🍎",
    ar: { letter: "ت", letterSpeech: "تاء", word: "تفاحة", wordSpeech: "تفاحة" },
    en: { letter: "A", letterSpeech: "A", word: "Apple", wordSpeech: "Apple" },
    fr: { letter: "P", letterSpeech: "P", word: "Pomme", wordSpeech: "Pomme" },
    de: { letter: "A", letterSpeech: "A", word: "Apfel", wordSpeech: "Apfel" },
  },
  {
    id: "banana",
    emoji: "🍌",
    ar: { letter: "م", letterSpeech: "ميم", word: "موزة", wordSpeech: "موزة" },
    en: { letter: "B", letterSpeech: "B", word: "Banana", wordSpeech: "Banana" },
    fr: { letter: "B", letterSpeech: "B", word: "Banane", wordSpeech: "Banane" },
    de: { letter: "B", letterSpeech: "B", word: "Banane", wordSpeech: "Banane" },
  },
  {
    id: "camel",
    emoji: "🐫",
    ar: { letter: "ج", letterSpeech: "جيم", word: "جمل", wordSpeech: "جمل" },
    en: { letter: "C", letterSpeech: "C", word: "Camel", wordSpeech: "Camel" },
    fr: { letter: "C", letterSpeech: "C", word: "Chameau", wordSpeech: "Chameau" },
    de: { letter: "K", letterSpeech: "K", word: "Kamel", wordSpeech: "Kamel" },
  },
  {
    id: "dolphin",
    emoji: "🐬",
    ar: { letter: "د", letterSpeech: "دال", word: "دولفين", wordSpeech: "دولفين" },
    en: { letter: "D", letterSpeech: "D", word: "Dolphin", wordSpeech: "Dolphin" },
    fr: { letter: "D", letterSpeech: "D", word: "Dauphin", wordSpeech: "Dauphin" },
    de: { letter: "D", letterSpeech: "D", word: "Delphin", wordSpeech: "Delphin" },
  },
  {
    id: "elephant",
    emoji: "🐘",
    ar: { letter: "ف", letterSpeech: "فاء", word: "فيل", wordSpeech: "فيل" },
    en: { letter: "E", letterSpeech: "E", word: "Elephant", wordSpeech: "Elephant" },
    fr: { letter: "E", letterSpeech: "E", word: "Éléphant", wordSpeech: "Éléphant" },
    de: { letter: "E", letterSpeech: "E", word: "Elefant", wordSpeech: "Elefant" },
  },
  {
    id: "frog",
    emoji: "🐸",
    ar: { letter: "ض", letterSpeech: "ضاد", word: "ضفدع", wordSpeech: "ضفدع" },
    en: { letter: "F", letterSpeech: "F", word: "Frog", wordSpeech: "Frog" },
    fr: { letter: "G", letterSpeech: "G", word: "Grenouille", wordSpeech: "Grenouille" },
    de: { letter: "F", letterSpeech: "F", word: "Frosch", wordSpeech: "Frosch" },
  },
  {
    id: "grape",
    emoji: "🍇",
    ar: { letter: "ع", letterSpeech: "عين", word: "عنب", wordSpeech: "عنب" },
    en: { letter: "G", letterSpeech: "G", word: "Grape", wordSpeech: "Grape" },
    fr: { letter: "R", letterSpeech: "R", word: "Raisin", wordSpeech: "Raisin" },
    de: { letter: "W", letterSpeech: "W", word: "Weintraube", wordSpeech: "Weintraube" },
  },
  {
    id: "rabbit",
    emoji: "🐰",
    ar: { letter: "أ", letterSpeech: "ألف", word: "أرنب", wordSpeech: "أرنب" },
    en: { letter: "R", letterSpeech: "R", word: "Rabbit", wordSpeech: "Rabbit" },
    fr: { letter: "L", letterSpeech: "L", word: "Lapin", wordSpeech: "Lapin" },
    de: { letter: "H", letterSpeech: "H", word: "Hase", wordSpeech: "Hase" },
  },
];

export const GAME_MODES: GameModeInfo[] = [
  {
    id: 1,
    unlockedByDefault: true,
    title: {
      ar: "حرف ↔ حرف",
      en: "Letter ↔ Letter",
      fr: "Lettre ↔ Lettre",
      de: "Buchstabe ↔ Buchstabe",
    },
    description: {
      ar: "طابق الحروف المتشابهة وتعلّم نطقها السليم!",
      en: "Match letters that look and sound the same!",
      fr: "Associe les lettres identiques et apprends leur son !",
      de: "Finde gleiche Buchstaben und lerne die Aussprache!",
    },
  },
  {
    id: 2,
    unlockedByDefault: false,
    title: {
      ar: "حرف ↔ صورة",
      en: "Letter ↔ Picture",
      fr: "Lettre ↔ Image",
      de: "Buchstabe ↔ Bild",
    },
    description: {
      ar: "طابق الحرف مع الصورة التي تبدأ به!",
      en: "Match the starting letter with the correct picture!",
      fr: "Associe la lettre de départ à la bonne image !",
      de: "Ordne den Anfangsbuchstaben dem richtigen Bild zu!",
    },
  },
  {
    id: 3,
    unlockedByDefault: false,
    title: {
      ar: "صورة ↔ كلمة",
      en: "Picture ↔ Word",
      fr: "Image ↔ Mot",
      de: "Bild ↔ Wort",
    },
    description: {
      ar: "طابق الصورة مع الكلمة المكتوبة المناسبة!",
      en: "Match the cute illustration with its written name!",
      fr: "Associe l'image mignonne à son mot écrit !",
      de: "Verbinde das niedliche Bild mit dem geschriebenen Wort!",
    },
  },
  {
    id: 4,
    unlockedByDefault: false,
    title: {
      ar: "صوت ↔ صورة",
      en: "Audio ↔ Picture",
      fr: "Audio ↔ Image",
      de: "Audio ↔ Bild",
    },
    description: {
      ar: "استمع لنطق الكلمة ثم ابحث عن صورتها الصحيحة!",
      en: "Listen to the word pronunciation and find the correct picture!",
      fr: "Écoute la prononciation du mot et trouve l'image !",
      de: "Hör dir die Aussprache an und finde das passende Bild!",
    },
  },
  {
    id: 5,
    unlockedByDefault: false,
    title: {
      ar: "صوت ↔ كلمة",
      en: "Audio ↔ Word",
      fr: "Audio ↔ Mot",
      de: "Audio ↔ Wort",
    },
    description: {
      ar: "استمع لنطق الكلمة ثم اختر الكلمة المكتوبة المطابقة!",
      en: "Listen to the word pronunciation and select the correct written word!",
      fr: "Écoute le mot parlé et sélectionne le mot écrit !",
      de: "Hör dir das Wort an und wähle das geschriebene Wort!",
    },
  },
];

export const TRANSLATIONS = {
  ar: {
    hubName: "إمباكت هاب مصر",
    hubDev: "طوّر بواسطة إمباكت هاب مصر",
    collectionName: "مجموعة ألعاب مصر التعليمية - لعبة رقم ٦",
    gameTitle: "مغامرة مطابقة الذاكرة ثلاثية الأبعاد",
    chooseLang: "اختر لغتك المفضلة للبدء",
    chooseMode: "اختر طريقة اللعب",
    chooseDifficulty: "اختر مستوى الصعوبة",
    stars: "النجوم",
    level: "المستوى",
    mode: "النمط",
    unlocked: "تم فتح القفل!",
    progress: "التقدم",
    restart: "إعادة البدء",
    home: "الرئيسية",
    soundOn: "تشغيل الصوت",
    soundOff: "كتم الصوت",
    screenshot: "شهادة نجاح",
    easy: "سهل (٣ أزواج)",
    medium: "متوسط (٤ أزواج)",
    hard: "صعب (٦ أزواج)",
    wellDone: "أحسنت يا بطل!",
    levelUnlockedMsg: "لقد فتحت مستوى جديداً!",
    playAgain: "العب مجدداً",
    nextLevel: "المستوى التالي",
    matches: "المطابقات",
    turns: "المحاولات",
    audioInstructions: "اضغط على السماعة لسماع الصوت!",
    back: "رجوع",
    certificateTitle: "شهادة بطل الذاكرة",
    certificateSub: "تمنح هذه الشهادة بكل فخر للبطل المتميز لإتمامه:",
    certificateDate: "التاريخ",
    certificateVerify: "مقدمة من إمباكت هاب مصر",
    cheatUnlock: "فتح جميع الأنماط للأهل والمعلمين",
    allUnlocked: "تم فتح جميع الأنماط!",
    promptFlipTwo: "اقلب بطاقتين للبحث عن أزواج متطابقة!",
    promptPressSpeaker: "اضغط على زر السماعة لسماع النطق!",
    matchFoundText: "رائع! تطابق ممتاز!",
    keepTryingText: "حاول مرة أخرى يا بطل!",
    loadingAudio: "جاري تحميل الصوت المميز...",
  },
  en: {
    hubName: "Impact Hub Egypt",
    hubDev: "Developed by Impact Hub Egypt",
    collectionName: "Egypt Educational Games Collection - Game #6",
    gameTitle: "3D Memory Match Adventure",
    chooseLang: "Choose your language to start",
    chooseMode: "Select Game Mode",
    chooseDifficulty: "Choose Difficulty",
    stars: "Stars",
    level: "Level",
    mode: "Mode",
    unlocked: "Unlocked!",
    progress: "Progress",
    restart: "Restart",
    home: "Home",
    soundOn: "Sound On",
    soundOff: "Mute Sound",
    screenshot: "Get Certificate",
    easy: "Easy (3 Pairs)",
    medium: "Medium (4 Pairs)",
    hard: "Hard (6 Pairs)",
    wellDone: "Well Done, Champ!",
    levelUnlockedMsg: "You have unlocked a new game mode!",
    playAgain: "Play Again",
    nextLevel: "Next Mode",
    matches: "Matches",
    turns: "Turns",
    audioInstructions: "Tap the speaker on the card to hear!",
    back: "Back",
    certificateTitle: "Memory Champ Certificate",
    certificateSub: "This certificate is proudly awarded to our amazing memory master for completing:",
    certificateDate: "Date",
    certificateVerify: "Verified by Impact Hub Egypt",
    cheatUnlock: "Parent/Teacher Bypass: Unlock All Modes",
    allUnlocked: "All modes successfully unlocked!",
    promptFlipTwo: "Flip any two cards to find a matching pair!",
    promptPressSpeaker: "Tap the speaker icon to play the sound!",
    matchFoundText: "Hooray! Perfect Match!",
    keepTryingText: "Keep trying, you can do it!",
    loadingAudio: "Loading magic voice...",
  },
  fr: {
    hubName: "Impact Hub Égypte",
    hubDev: "Développé par Impact Hub Égypte",
    collectionName: "Collection d'jeux Éducatifs d'Égypte - Jeu #6",
    gameTitle: "Aventure de Mémoire 3D",
    chooseLang: "Choisissez votre langue pour commencer",
    chooseMode: "Sélectionnez le mode de jeu",
    chooseDifficulty: "Choisissez la difficulté",
    stars: "Étoiles",
    level: "Niveau",
    mode: "Mode",
    unlocked: "Débloqué !",
    progress: "Progrès",
    restart: "Recommencer",
    home: "Accueil",
    soundOn: "Son Activé",
    soundOff: "Couper le Son",
    screenshot: "Certificat",
    easy: "Facile (3 paires)",
    medium: "Moyen (4 paires)",
    hard: "Difficile (6 paires)",
    wellDone: "Bien joué, Champion !",
    levelUnlockedMsg: "Tu as débloqué un nouveau mode de jeu !",
    playAgain: "Rejouer",
    nextLevel: "Mode Suivant",
    matches: "Paires",
    turns: "Essais",
    audioInstructions: "Appuie sur le haut-parleur de la carte !",
    back: "Retour",
    certificateTitle: "Certificat de Champion de Mémoire",
    certificateSub: "Ce certificat est fièrement décerné à notre super maître de mémoire pour avoir terminé :",
    certificateDate: "Date",
    certificateVerify: "Vérifié par Impact Hub Égypte",
    cheatUnlock: "Contrôle Parental : Débloquer tout",
    allUnlocked: "Tous les modes débloqués !",
    promptFlipTwo: "Retourne deux cartes pour trouver une paire !",
    promptPressSpeaker: "Appuie sur le haut-parleur pour entendre !",
    matchFoundText: "Super ! Une paire assortie !",
    keepTryingText: "Continue d'essayer, tu vas y arriver !",
    loadingAudio: "Chargement de la voix magique...",
  },
  de: {
    hubName: "Impact Hub Ägypten",
    hubDev: "Entwickelt von Impact Hub Ägypten",
    collectionName: "Ägypten Lernspiel-Sammlung - Spiel #6",
    gameTitle: "3D-Gedächtnis-Abenteuer",
    chooseLang: "Wähle deine Sprache zum Starten",
    chooseMode: "Wähle den Spielmodus",
    chooseDifficulty: "Schwierigkeit wählen",
    stars: "Sterne",
    level: "Stufe",
    mode: "Modus",
    unlocked: "Freigeschaltet!",
    progress: "Fortschritt",
    restart: "Neustart",
    home: "Hauptmenü",
    soundOn: "Ton An",
    soundOff: "Stumm schalten",
    screenshot: "Zertifikat",
    easy: "Einfach (3 Paare)",
    medium: "Mittel (4 Paare)",
    hard: "Schwer (6 Paare)",
    wellDone: "Gut gemacht, Champion!",
    levelUnlockedMsg: "Du hast einen neuen Spielmodus freigeschaltet!",
    playAgain: "Nochmal spielen",
    nextLevel: "Nächster Modus",
    matches: "Paare",
    turns: "Versuche",
    audioInstructions: "Tippe auf den Lautsprecher, um zu hören!",
    back: "Zurück",
    certificateTitle: "Gedächtnis-Champion-Zertifikat",
    certificateSub: "Dieses Zertifikat wird unserem fantastischen Gedächtnismeister verliehen für:",
    certificateDate: "Datum",
    certificateVerify: "Verifiziert durch Impact Hub Ägypten",
    cheatUnlock: "Eltern-Bypass: Alle Modi freischalten",
    allUnlocked: "Alle Modi erfolgreich freigeschaltet!",
    promptFlipTwo: "Drehe zwei Karten um, um ein Paar zu finden!",
    promptPressSpeaker: "Tippe auf den Lautsprecher für den Ton!",
    matchFoundText: "Hurra! Perfektes Paar gefunden!",
    keepTryingText: "Versuch es weiter, du schaffst das!",
    loadingAudio: "Lade magische Stimme...",
  },
};
